trigger:
 - master
pool:
  name: Hosted Ubuntu 1604
steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment:Create Azure Container Registry'
  inputs:
    azureSubscription: 'msbuild2019-python - Service Endpoint'
    resourceGroupName: 'msbuild2019-python-rg'
    location: 'West US 2'
    csmFile: '$(System.DefaultWorkingDirectory)/**/containerRegistry-template.json'
    overrideParameters: '-registryName "msbuild2019pythonacr" -registryLocation "South Central US" -registrySku "Standard"'

- task: UsePythonVersion@0
  displayName: 'Use Python 2.x'
  inputs:
    versionSpec: 2.x

- script: 'pip install -r Application/requirements.txt'
  displayName: 'Install Dependencies'

- script: 'pip install pytest && pytest Tests/unit_tests --junitxml=../TestResults/test-results.xml && pip install pycmd && py.cleanup Tests/'
  displayName: Pytest

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-*.xml'
  inputs:
    testResultsFiles: '**/test-*.xml'
    searchFolder: '$(Common.TestResultsDirectory)'

- task: ArchiveFiles@1
  displayName: 'Archive tests'
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)/Tests'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/Tests$(Build.BuildId).zip'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'msbuild2019-python - Service Endpoint'
    azureContainerRegistry: msbuild2019pythonacr.azurecr.io
    imageName: 'msbuild2019python:$(Build.BuildId)'
    useDefaultContext: false
    buildContext: '$(System.DefaultWorkingDirectory)/Application'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'msbuild2019-python - Service Endpoint'
    azureContainerRegistry: '{"loginServer":"msbuild2019pythonacr.azurecr.io", "id" : "/subscriptions/3a06a10f-ae29-4924-b6a7-dda0ea91d347/resourceGroups/msbuild2019-python-rg/providers/Microsoft.ContainerRegistry/registries/msbuild2019pythonacr"}'
    command: 'Push an image'
    imageName: 'msbuild2019python:$(Build.BuildId)'

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: ArmTemplates
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
